##### BACKGROUND OPACITY #####

background_opacity 0.25

# background_opacity  0.7
# enable_audio_bell   no

#FONT#
font_family GeistMono Nerd Font Mono
font_size 13


disable_ligatures no\
enable_audio_bell no

#SHELL#
shell zsh
shell_integration disabled

#CURSOR#
cursor_shape underline

#URL#
url_style curly

#WINDOW#
#To let kitty remember the settings of the screen#
remember_window_size no

#Kitty Look and Feel#
  #initial_window_width 360
  #initial_window_height 250
  #window_padding_width 15
  #cursor_blink_interval -25
  #scrollbar_handle_opacity 5
  scrollbar_track_opacity 5
  scrollbar_track_hover_opacity 5
  confirm_os_window_close 0
  
#RefreshRate of the Monitor#
sync_to_monitor no

# COLOR FOR KITTY #
background #1b1d1e
foreground #f8f8f8
cursor #fc971e
selection_background #4d4d4d
color0 #1b1d1e
color8 #505354
color1 #f92672
color9 #ff5995
color2 #4df740
color10 #b6e354
color3 #f3fd21
color11 #feed6c
color4 #2656d6
color12 #3f78ff
color5 #8c54fe
color13 #9e6ffe
color6 #37c8b4
color14 #23ced4
color7 #ccccc6
color15 #f8f8f2
selection_foreground #1b1d1e

ls = eza -icons
